import { BlogPost } from '../types';
import frontMatter from 'front-matter';

// Fetches the index generated by the build script
export async function getBlogPosts(): Promise<BlogPost[]> {
  try {
    const response = await fetch('/blog-index.json');
    if (!response.ok) throw new Error('Failed to load blog index');
    const posts = await response.json();
    
    // Map JSON data to our BlogPost type, adding empty content array as fallback
    // The index only has excerpts, full content is fetched individually
    return posts.map((p: any) => ({
      ...p,
      imageColor: 'bg-brand-dark', // Default fallback
      content: [] 
    }));
  } catch (error) {
    console.error(error);
    return [];
  }
}

export async function getBlogPost(id: string): Promise<BlogPost | null> {
  try {
    const response = await fetch(`/content/blog/${id}.md`);
    if (!response.ok) return null;
    
    const text = await response.text();
    const { attributes, body } = frontMatter<any>(text);
    
    return {
      id,
      title: attributes.title,
      date: attributes.date,
      category: attributes.category,
      readTime: attributes.readTime,
      excerpt: attributes.excerpt,
      imageColor: 'bg-brand-dark',
      content: [body] // We pass the raw markdown body as a single string for react-markdown
    };
  } catch (error) {
    console.error(error);
    return null;
  }
}